name: NPM-Publisher-Test

on:
  push:
    branches: [test-npm-publish]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - run: npm install -g typescript

      - name: Build acbrlib-base-node
        working-directory: acbrlib-base-node
        run: |
          npm install
          npm run build
          
      - name: Publish acbrlib-base-node
        working-directory: acbrlib-base-node
        run: |
          npm version patch
          npm publish --access public
      
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
