name: NPM-Publisher-Test

on:
  push:
    branches: [test-npm-publish]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install -g typescript yalc

      - name: Build comum
        run: |
          cd acbrlib-base-node
          npm install
          npm run build
          yalc publish
      
  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: |
          cd acbrlib-base-node
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
